[build]
  command = "eleventy"
  publish = "_site"

[[edge_functions]]
  path = "/*"
  function = "protect"
  [edge_functions.environment]
    SITE_BASIC_AUTH_USER = "${SITE_BASIC_AUTH_USER}"
    SITE_BASIC_AUTH_PASS = "${SITE_BASIC_AUTH_PASS}"

[[redirects]]
  from = "/api/transcribe"
  to = "/.netlify/functions/transcribe"
  status = 200

[[redirects]]
  from = "/api/ics"
  to = "/.netlify/functions/ics"
  status = 200

[[redirects]]
  from = "/api/links"
  to = "/.netlify/functions/links"
  status = 200

[[redirects]]
  from = "/api/ideas"
  to = "/.netlify/functions/ideas"
  status = 200
